---
- name: Install needed helper package(s)
  become: true
  become_method: sudo
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - unzip

- name: Check for previously installed and executable packer
  shell: "packer version | head -n1 | awk '{print $2}' | awk -F'-' '{print $1}' | sed 's/v//'"
  changed_when: False
  failed_when: False
  register: prior_packer_version

- name: Previous packer version
  debug:
    var: prior_packer_version.stdout

- name: Convert architecture fact to what packer url structure expects - amd64
  set_fact:
    override_ansible_userspace_architecture: amd64
  when: ansible_userspace_architecture == "x86_64"

- name: Build base part of packer filename
  set_fact:
    packer_filename: "packer_{{ packer_version }}_{{ ansible_system|lower }}_{{ override_ansible_userspace_architecture|default('ansible_userspace_architecture') }}.zip"

- name: Get packer sha256sums
  get_url:
    url: "https://releases.hashicorp.com/packer/{{ packer_version }}/packer_{{ packer_version }}_SHA256SUMS"
    dest: "/tmp/packer_{{ packer_version }}_SHA256SUMS"
  when: prior_packer_version.stdout != packer_version

- name: Get packer sha256sum signatures
  get_url:
    url: "https://releases.hashicorp.com/packer/{{ packer_version }}/packer_{{ packer_version }}_SHA256SUMS.sig"
    dest: "/tmp/packer_{{ packer_version }}_SHA256SUMS.sig"
  when: prior_packer_version.stdout != packer_version

- name: Import the Hashicorp Security gpg key
  become: true
  become_method: sudo
  shell: curl https://keybase.io/hashicorp/key.asc | gpg --import
  args:
    warn: False
  changed_when: False
  when: prior_packer_version.stdout != packer_version

- name: Verify the signature file is untampered
  become: true
  become_method: sudo
  command: "gpg --verify /tmp/packer_{{ packer_version }}_SHA256SUMS.sig /tmp/packer_{{ packer_version }}_SHA256SUMS"
  register: sha256_check
  changed_when: False
  failed_when: '"Good signature from \"HashiCorp Security <security@hashicorp.com>\"" not in sha256_check.stderr'
  when: prior_packer_version.stdout != packer_version

- name: "Gather signature for {{ packer_filename }}"
  shell: "grep '{{ packer_filename }}' /tmp/packer_{{ packer_version }}_SHA256SUMS | awk '{print $1}'"
  changed_when: False
  register: packer_signature
  when: prior_packer_version.stdout != packer_version

- name: "Download {{ packer_filename }}"
  get_url:
    url: "https://releases.hashicorp.com/packer/{{ packer_version }}/{{ packer_filename }}"
    dest: "/tmp/{{ packer_filename }}"
    checksum: "sha256:{{ packer_signature.stdout }}"
    owner: root
    group: root
    mode: 0444
  when: prior_packer_version.stdout != packer_version

- name: Install packer from the zip
  become: true
  become_method: sudo
  unarchive:
    src: "/tmp/{{ packer_filename }}"
    dest: "/bin"
    copy: no
    mode: 0775
    owner: root
    group: root
    seuser: system_u
    serole: object_r
    setype: bin_t
    selevel: s0
  when: prior_packer_version.stdout != packer_version
...
